name: SubFinder
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Apex domain'
        default: 'king.com'
        required: true
jobs:
  SubFinder:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: 🔎 SubFinder - DNS Enumeration
      uses: projectdiscovery/subfinder-action@main
      with:
        domain: "${{ github.event.inputs.name }}"
        active: true
        json: true
