# This is a basic workflow that is manually triggered

name: SubFinder - DNS Enumeration - Manual
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Apex domain'
        # Default value if no value is explicitly provided
        default: 'king.com'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: 🔎 SubFinder - DNS Enumeration
      uses: projectdiscovery/subfinder-action@main
      with:
        domain: "${{ github.event.inputs.name }}"
